### ISSUE TITLE
Arduino gpio "value" file content stuck 

### ISSUE THREAD

**Issue by phtrivier** [linino/linino_distro#9]
Hi 

 I have an Arduino Yun running lininoio.
I run code that does the equivalent of : 
* echoing 117 to `/sys/class/gpio/export` so that GPIO D2 is available as `/sys/class/gpio/D2/xxx`
* open the value file  `/sys/class/gpio/D2/value` to get a gpio_id
* read the file's content

On the board, the D2 pin is connected to the power voltage with a switch (I'm using the 'value' file to check whether the switch is on or off.)
Everything works fine when the program runs for a short while (the 'value' file is changed to either 0 or 1), but regularly, the board ends up in a state when there is no synchro between the pin and the value file.

(I can even confirm the desynchro in a shell, outside of my program.)

I get the synchro again by stopping and restarting lininoio.

What are potentials causes for such a desynchro ? What could I check to diagnose it ?

Thanks

**Comment by colosimo** [comment]
Hi Pierre

First of all, can you please tell me the version you are using? Please type:

uname -a

... and send me the output.

Also, I think the first thing you can do is type "dmesg" on your console 
and see if you notice something strange... or send me the content of 
dmesg, so that I can analyze it.

In a second step, we might enable more verbose log messages, but this 
may involve the re-compiling of kernel or MCU firmware (bathos).

Please update me with the required information, then we'll see how to 
proceed.

Thanks

Aurelio

**Comment by phtrivier** [comment]
Hi

 here is the output from uname : 

~~~
root@yun01:~# uname -a
Linux yun01 3.3.8 #1 Wed Nov 11 12:29:46 CET 2015 mips GNU/Linux
~~~

Assuming "mcuio" is the relevant part of dmesg output, here is something I get both when the syncing works and when it fails

~~~
[   51.060000] mcuio adc is 0:1:1
[   51.060000] mcuio-adc 0:1.1: 6 input channels detected
[   51.130000] mcuio pwm is 0:1:2
[   51.130000] mcuio-pwm 0:1.2: 6 pwm outputs detected
~~~

Here is something I only get when the syncing fails
~~~
[ 6937.920000] mcuio_gpio_input: error reading curr config
[ 6938.530000] mcuio_gpio_output: error reading curr config
[ 7116.600000] mcuio_gpio_input: error reading curr config
[ 7117.210000] mcuio_gpio_output: error reading curr config
~~~

Note that contrary to what I first said, simply rebooting the device fixes the syncing issue. 

Any hint on how I could get more information ? 

Thanks

**Comment by colosimo** [comment]
Hi Pierre

the "error reading" stuff you're seeing in dmesg is most probably the 
cause of your problem. Seems like there is a communication data loss 
between MPU and MCU. You can try to modify the baudrate on UART:

1) check the content of /etc/config/mcuiocfg
You should see something like:
export BAUDRATE=460800

2) slow down above BAUDRATE value to 230400:
export BAUDRATE=230400

Please let me know if this solution fixes your problem.

Thanks

Aurelio


On 07/01/2016 12:26, Pierre-Henri Trivier wrote:
> Hi
>
> here is the output from uname :
>
> |root@yun01:~# uname -a Linux yun01 3.3.8 #1 Wed Nov 11 12:29:46 CET 2015
> mips GNU/Linux |
>
> Assuming "mcuio" is the relevant part of dmesg output, here is something
> I get both when the syncing works and when it fails
>
> |[ 51.060000] mcuio adc is 0:1:1 [ 51.060000] mcuio-adc 0:1.1: 6 input
> channels detected [ 51.130000] mcuio pwm is 0:1:2 [ 51.130000] mcuio-pwm
> 0:1.2: 6 pwm outputs detected |
>
> Here is something I only get when the syncing fails
>
> |[ 6937.920000] mcuio_gpio_input: error reading curr config [
> 6938.530000] mcuio_gpio_output: error reading curr config [ 7116.600000]
> mcuio_gpio_input: error reading curr config [ 7117.210000]
> mcuio_gpio_output: error reading curr config |
>
> Note that contrary to what I first said, simply rebooting the device
> fixes the syncing issue.
>
> Any hint on how I could get more information ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linino/linino_distro/issues/9#issuecomment-169635074>.
>


-- 
Ing. Aurelio Colosimo
Via Ferrante Aporti, 54
20125 Milano - Italy
Tel: +39 0289692946
Cell: +39 3335948817
Web: www.aureliocolosimo.it
e-mail: aurelio@aureliocolosimo.it

**Comment by phtrivier** [comment]
Hi ! Slowing BAUDRATE does not seem to fix the issue (I still get either 'error reading curr config', or 'unable to read io' messages.)

**Comment by colosimo** [comment]
Hi Pierre

Maybe you're stressing our lininoIO code in a different manner than we 
did in our tests, so something weird and unpredicted is happening.

I think the best thing we can do is trying to reproduce the bug in my 
lab. If it's possible for you, could you please send me the code you're 
running?

To help me understand what does your code do, could you please answer to 
these questions:
- you said you're polling gpio D2; what is the polling interval, in 
time, between two consecutive reads of D2 value?
- did you try to use gpio interrupts instead of polling? This would be 
much more efficient, if I'm understanding your needs;
- is there anything else the system is doing while the polling is ongoing?
- is there anything happening on some certain conditions?
- is there a particular circuitry would I need to reproduce the bug?

Thanks!

Aurelio

**Comment by phtrivier** [comment]
Ok, the full code for what I'm doing is available here : https://github.com/phtrivier/wakaama/blob/pht/linino-gpio/tests/client/lwm2mclient.c

Here is some context : 
* the program is an example of how to use a networking library for LWM2M protocol
* the code used to listen a network socket (for communication) and stdin (for various instructions)
* I wanted to add using gpios to actually send data to a LWM2M server
* for example, I wanted to read a digital input on D2 with the following montage : http://labs.arduino.org/ArduinoYUN+Button+Example

The main poll is doing this : 

* given file descriptors for stdin and the network socket
* open a file descriptor on gpio D2
* select on any of the file

~~~
FD_ZERO(&readfds);
FD_SET(data.sock, &readfds);
FD_SET(STDIN_FILENO, &readfds);
...
int gpio_fd = gpio_fd_open(...);
FD_SET(gpio_fd, &readfds);
...
result = select(FD_SETSIZE, &readfds, NULL, NULL, &tv);
~~~

* if something was read on network / stdin, react, otherwise, the content of the file is the only thing that will get read (and it always will), so we read the content.

~~~
if (FD_ISSET(data.sock, &readfds)) {
  ...
} else if (FD_ISSET(STDIN_FILENO, &readfds)) {
  ...
} else if (FD_ISSET(gpio_fd, &readfds)) {
  // Read gpio file value
  // Close gpio (ugly, but could not find a way to read new value)
}
~~~
 
Other part of the code will check if we read a new value (in which case we send it to the server) or the same value.

Ideally, I would have preferred a way to select or poll only for *changes* in the /sys/class/gpio/D2/value file. 
I tried using pselect or poll instead, but could not find a way.

So clearly, I'm probably reading at a very high rate (since most of the time, the network and stdin will not be active...)

What do you mean by "gpio interrupts" ? Which function would I use for that ?

Thanks

**Comment by colosimo** [comment]
Hi Pierre
thanks for the information. Here below my answers

 > Ok, the full code for what I'm doing is available here :
> https://github.com/phtrivier/wakaama/blob/pht/linino-gpio/tests/client/lwm2mclient.c

Thanks, I will take a look.

> Here is some context :
> [...]

Ok, it's clear.

> Ideally, I would have preferred a way to select or poll only for
> /changes/ in the /sys/class/gpio/D2/value file.
> I tried using pselect or poll instead, but could not find a way.

Yes, that's what I was proposing you.
You have to enable the poll function, by writing "both", "raising" or 
"falling" to /sys/class/gpio/D2/edge

echo both > /sys/class/gpio/D2/edge
     or
echo raising > /sys/class/gpio/D2/edge
     or
echo falling > /sys/class/gpio/D2/edge

> So clearly, I'm probably reading at a very high rate (since most of the
> time, the network and stdin will not be active...)

Yes, if you think rate is very high, maybe our AVR MCU is not fast 
enough to reply correctly at such a high rate, so, sooner or later, it 
starts losing some data.

> What do you mean by "gpio interrupts" ? Which function would I use for
> that ?

"GPIO interrupts" are handled on kernel side: it is a way to associate 
an interrupt to a raise, fall or both edges of a gpio. When it's 
enabled, poll syscall will work on "value" file changes. You can enable 
it with the above edge sysfs attribute.

A more detailed explanation is on Documentation/gpio/sysfs.txt:

https://www.kernel.org/doc/Documentation/gpio/sysfs.txt

Read, for instance, this piece of text:

	"edge" ... reads as either "none", "rising", "falling", or
		"both". Write these strings to select the signal edge(s)
		that will make poll(2) on the "value" file return.

		This file exists only if the pin can be configured as an
		interrupt generating input pin.

I hope that, with this mechanism, you should be able to fix your 
problem. If not, please tell me and I will provide some example src code.

Just let me know!

Aurelio

**Comment by phtrivier** [comment]
Hi again. Unfortunately, it does not seem to work as I expect.
I'm now doing this something like this :

* I tried using D3 instead of D2 
* Assume `/sys/class/gpio/D3/edge` reads `both`
* I'll create two fd_set (one for socket / stding, one for 'interrupts' - as described in the sysfs doc, if I read it correctly)

~~~
// Assuming : 
// echo both > /sys/class/gpio/D3/edge

FD_ZERO(&readfds);
FD_SET(data.sock, &readfds);
FD_SET(STDIN_FILENO, &readfds);
...
FD_ZERO(&exceptfds);
int gpio_fd = gpio_fd_open(...);
FD_SET(gpio_fd, &exceptfds);
...
result = select(FD_SETSIZE, &readfds, NULL, &exceptfds &tv);
~~~

Then checking like this : 

~~~
if (FD_ISSET(data.sock, &readfds)) {
  ...
} else if (FD_ISSET(STDIN_FILENO, &readfds)) {
  ...
} else if (FD_ISSET(gpio_fd, &exceptfds) {
  printf("Something read");
  // Read gpio file value
  // Close gpio (ugly, but could not find a way to read new value)
}
~~~

the `exceptfds` part of the loop is always called (even without touching the button), no matter what the content of `edge` file is. I was assuming it would only be set when the content of the file changed.

So if you code for this is available somewhere, a pointer would be nice. 

Thanks for you help !

**Comment by colosimo** [comment]
Ok I will check your code and/or propose mine.

Or, if someone else in this mailing list has a sample code for gpio 
interrupts handling, maybe he/she can help you. As far as I remember, 
someone wrote a poll-test application used for testing purposes, maybe 
it can be shared.

In any case, I will be back to you tomorrow.

Bye

Aurelio



On 13/01/2016 17:17, Pierre-Henri Trivier wrote:
> Hi again. Unfortunately, it does not seem to work as I expect.
> I'm now doing this something like this :
>
>   * I tried using D3 instead of D2
>   * Assume |/sys/class/gpio/D3/edge| reads |both|
>   * I'll create two fd_set (one for socket / stding, one for
>     'interrupts' - as described in the sysfs doc, if I read it correctly)
>
> |// Assuming : // echo both > /sys/class/gpio/D3/edge FD_ZERO(&readfds);
> FD_SET(data.sock, &readfds); FD_SET(STDIN_FILENO, &readfds); ...
> FD_ZERO(&exceptfds); int gpio_fd = gpio_fd_open(...); FD_SET(gpio_fd,
> &exceptfds); ... result = select(FD_SETSIZE, &readfds, NULL, &exceptfds
> &tv); |
>
> Then checking like this :
>
> |if (FD_ISSET(data.sock, &readfds)) { ... } else if
> (FD_ISSET(STDIN_FILENO, &readfds)) { ... } else if (FD_ISSET(gpio_fd,
> &exceptfds) { printf("Something read"); // Read gpio file value // Close
> gpio (ugly, but could not find a way to read new value) } |
>
> the |exceptfds| part of the loop is always called (even without touching
> the button), no matter what the content of |edge| file is. I was
> assuming it would only be set when the content of the file changed.
>
> So if you code for this is available somewhere, a pointer would be nice.
>
> Thanks for you help !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linino/linino_distro/issues/9#issuecomment-171346994>.
>


-- 
Ing. Aurelio Colosimo
Via Ferrante Aporti, 54
20125 Milano - Italy
Tel: +39 0289692946
Cell: +39 3335948817
Web: www.aureliocolosimo.it
e-mail: aurelio@aureliocolosimo.it

**Comment by ciminaghi** [comment]
On Wed, Jan 13, 2016 at 08:35:05AM -0800, Aurelio Colosimo wrote:
> Ok I will check your code and/or propose mine.
> 
> Or, if someone else in this mailing list has a sample code for gpio 
> interrupts handling, maybe he/she can help you. As far as I remember, 
> someone wrote a poll-test application used for testing purposes, maybe 
> it can be shared.
>
attached some test code. It is old and unofficial, so it should more or less
work, but I can't remember exactly what the programs do and how to use them.
The thing to keep in mind is that there's no check on the number of args
passed via command line, so you should have a look at the sources
and understand what the programs do and what args they expect.
If you pass less arguments than needed you'll got a crash. This task
shouldn't bee to difficult, though, since all programs are just some tens
lines long.
For instance poll-test.c waits for a gpio to change its status, and gets the
path of the corresponding sysfs file as first argument, so I think it
could be useful.

Hope this helps
Davide

**Comment by phtrivier** [comment]
@ciminaghi Did you try attaching something ? (sorry I'm just not seiing poll-test.c)

**Comment by ciminaghi** [comment]
On Wed, Jan 13, 2016 at 09:12:29AM -0800, Pierre-Henri Trivier wrote:
> @ciminaghi Did you try attaching something ? (sorry I'm just not seiing poll-test.c)
>
yes I did. [test.tar.gz]. I'll try attaching the .c files directly

Davide

**Comment by phtrivier** [comment]
(I think when replying to pull requests via email, the attachement are ignored. Could you attach them from github site ? Sorry about that...)

**Comment by colosimo** [comment]
Hi all

I'm afraid github is filtering attachments.

I copied Davide's src files on my server, renaming them as 
gpio_poll_test.tar.gz. Here is the link:

www.aureliocolosimo.it/gpio_poll_test.tar.gz

I think you can try to compile and run them as stand-alone test 
applications; especially I suggest poll-test.c.

@Pierre: I'm not sure you need to close your file descriptor each time.

...
} else if (FD_ISSET(gpio_fd, &exceptfds) {
   printf("Something read");
   // Read gpio file value
   // Close gpio (ugly, but could not find a way to read new value)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}
...

As far as I know, you can open fd once and then perform any read each 
time you want to know the updated value: this is not a normal "file", 
this is a sysfs file, so each read should return the value.

Maybe that close makes something behave in a non-standard way, and cause 
your bug.

Aurelio



On 13/01/2016 23:02, Davide Ciminaghi wrote:
> On Wed, Jan 13, 2016 at 09:12:29AM -0800, Pierre-Henri Trivier wrote:
>  > @ciminaghi Did you try attaching something ? (sorry I'm just not
> seiing poll-test.c)
>  >
> yes I did. [test.tar.gz]. I'll try attaching the .c files directly
>
> Davide
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linino/linino_distro/issues/9#issuecomment-171451298>.
>


-- 
Ing. Aurelio Colosimo
Via Ferrante Aporti, 54
20125 Milano - Italy
Tel: +39 0289692946
Cell: +39 3335948817
Web: www.aureliocolosimo.it
e-mail: aurelio@aureliocolosimo.it

**Comment by ciminaghi** [comment]
On Thu, Jan 14, 2016 at 01:34:25AM -0800, Aurelio Colosimo wrote:
> Hi all
> 
> I'm afraid github is filtering attachments.
> 
> I copied Davide's src files on my server, renaming them as 
> gpio_poll_test.tar.gz. Here is the link:
> 
> www.aureliocolosimo.it/gpio_poll_test.tar.gz
> 
> I think you can try to compile and run them as stand-alone test 
> applications; especially I suggest poll-test.c.
> 
> @Pierre: I'm not sure you need to close your file descriptor each time.
> 
> ...
> } else if (FD_ISSET(gpio_fd, &exceptfds) {
>    printf("Something read");
>    // Read gpio file value
>    // Close gpio (ugly, but could not find a way to read new value)
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> }
> ...
> 
> As far as I know, you can open fd once and then perform any read each 
> time you want to know the updated value: this is not a normal "file", 
> this is a sysfs file, so each read should return the value.
>
if you don't want to close/open repeatedly, you have to do lseek(2) to 0 on the
file descriptor, or you can use pread(2) with offset 0.
poll-test.c does lseek(), while poll-test-out.c goes for pread().

Generally speaking, pread()/pwrite() should be slightly better than
read()/write() + lseek because you save one syscall.
Closing and reopening should be ok, provided that you update your fdset(s)
correctly (I haven't read your code yet). However, I thinks it's probably
significantly slower than keeping the file open (I haven't measured the
open/close overhead, though, so I might be wrong).

Thanks
Davide

**Comment by ciminaghi** [comment]
On Thu, Jan 14, 2016 at 01:31:26AM -0800, Pierre-Henri Trivier wrote:
> (I think when replying to pull requests via email, the attachement are ignored. Could you attach them from github site ? Sorry about that...)
> 
hi,

did you solve the problem ? Or are you still stuck ?
Just curious ....

Thanks
Davide

**Comment by phtrivier** [comment]
@ciminaghi using `lseek` and keeping the file descriptor open helped for a while ; however I still had issues after that. I'm starting to wonder if this is not strictly a board issue, but I'm not going to be able to test with another board for a while. So I'm closing the issue for the moment. 

Thanks a lot for the help though, I learnt a lot !

**Comment by ciminaghi** [comment]
On Thu, Jan 28, 2016 at 02:09:41AM -0800, Pierre-Henri Trivier wrote:
> @ciminaghi using `lseek` and keeping the file descriptor open helped for a while ; however I still had issues after that. I'm starting to wonder if this is not strictly a board issue, but I'm not going to be able to test with another board for a while. So I'm closing the issue for the moment. 
> 
> Thanks a lot for the help though, I learnt a lot !
>
it was a pleasure. Please let us know if you need more help.

Thanks and regards
Davide
